/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.cells.returned;

import raven.cells.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ayu novianingrum
 */
public class PanelAction extends javax.swing.JPanel {
    boolean Overdue = false;
    boolean hasReturned = false;

    /**
     * Creates new form PanelAction
     */
    public PanelAction(boolean Overdue, boolean hasReturned) {
        initComponents();
        this.Overdue = Overdue;
        this.hasReturned = hasReturned;
        actRemind.setVisible(Overdue);
        actReturn.setVisible(!hasReturned);
    }
    
    public void initEvent(TableActionEvent event, int row) {
        actReturn.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onReturn(row);
            }  
        });
        
        actRemind.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onRemind(row);
            }  
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actReturn = new raven.cells.CellActionButton();
        actRemind = new raven.cells.CellActionButton();

        setLayout(new java.awt.GridLayout());

        actReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/cells/returned/recovery.png"))); // NOI18N
        actReturn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actReturnActionPerformed(evt);
            }
        });
        add(actReturn);

        actRemind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/cells/returned/notification.png"))); // NOI18N
        actRemind.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actRemind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actRemindActionPerformed(evt);
            }
        });
        add(actRemind);
    }// </editor-fold>//GEN-END:initComponents

    private void actReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actReturnActionPerformed

    private void actRemindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actRemindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actRemindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.cells.CellActionButton actRemind;
    private raven.cells.CellActionButton actReturn;
    // End of variables declaration//GEN-END:variables
}
