/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.cells;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ayu novianingrum
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent event, int row) {
        actEdit.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onEdit(row);
            }  
        });
        
        actDelete.addActionListener(new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onDelete(row);
            }  
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actEdit = new raven.cells.CellActionButton();
        actDelete = new raven.cells.CellActionButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLayout(new java.awt.GridLayout());

        actEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/cells/write.png"))); // NOI18N
        actEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actEditActionPerformed(evt);
            }
        });
        add(actEdit);

        actDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/raven/cells/delete.png"))); // NOI18N
        actDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        actDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actDeleteActionPerformed(evt);
            }
        });
        add(actDelete);
    }// </editor-fold>//GEN-END:initComponents

    private void actEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actEditActionPerformed

    private void actDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.cells.CellActionButton actDelete;
    private raven.cells.CellActionButton actEdit;
    // End of variables declaration//GEN-END:variables
}
